# Generated by Django 4.0.1 on 2022-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
                ('zoom_meet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('panel_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('avg_score', models.IntegerField(blank=True, null=True)),
                ('panelmember_comments', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
