# Generated by Django 4.0.1 on 2022-06-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panelmember', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmember',
            name='panelmember_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='proposal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.proposal'),
        ),
    ]
