# Generated by Django 4.0.1 on 2022-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('reviewer_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('POSTER', 'Poster'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=100)),
                ('flag', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerScores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
