# Generated by Django 4.0.1 on 2022-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('abstract', models.CharField(blank=True, max_length=1500, null=True)),
                ('summary', models.CharField(blank=True, max_length=1500, null=True)),
                ('keypoints', models.CharField(blank=True, max_length=1500, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='proposal_documents/')),
                ('plagarism_doc', models.FileField(blank=True, null=True, upload_to='plagarism/')),
                ('re_documents', models.FileField(blank=True, null=True, upload_to='reup_documents/')),
                ('plagarism_score', models.IntegerField(blank=True, null=True)),
                ('doc_scanid', models.IntegerField(blank=True, null=True)),
                ('proposal_date', models.DateField(blank=True, null=True)),
                ('plagiarism', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('re_upload', models.BooleanField(blank=True, default=False, null=True)),
                ('proposal_status', models.IntegerField(blank=True, default=0, null=True)),
                ('total_panel_count', models.IntegerField(blank=True, default=0, null=True)),
                ('result_panel_count', models.IntegerField(blank=True, default=0, null=True)),
                ('rejected_by', models.IntegerField(blank=True, null=True)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('supervisor_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewers', models.CharField(blank=True, max_length=500, null=True)),
                ('meetingid', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_start_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
